version: '3.8'

services:
  api:
    build:
      target: runner
    image: pjatk21/pja-api
    ports:
      - "3333:3333"
    env_file:
     - .docker.env
    restart: always
  tasks:
    build:
      target: builder
    image: pjatk21/pja-api
    env_file:
     - .docker.env
    restart: always
    entrypoint: npm run tasks
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: adonisjs
      POSTGRES_PASSWORD: "w9ox!na6a#LwP@p!YJ4N"
      POSTGRES_DB: "pja-api"
    restart: always
