version: '3.8'

services:
  api:
    build: .
    image: pjatk21/pja-api
    ports:
      - "3333:3333"
    env_file:
     - .docker.env
    restart: unless-stopped
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: adonisjs
      POSTGRES_PASSWORD: "w9ox!na6a#LwP@p!YJ4N"