version: '3.8'

services:
  api:
    build:
      context: .
      target: builder
    ports:
      - "3333:3333"
    env_file:
      - .docker.env
    restart: always
    depends_on:
      - db
    entrypoint: npm run dev
  poller:
    build:
      context: .
      target: builder
    env_file:
      - .docker.env
    depends_on:
      - db
    restart: always
    cap_add:
      - "SYS_ADMIN"
    entrypoint: npm run poll
  db:
    image: postgres:14
    env_file:
      - .docker.env
    restart: always
